### ISSUE TITLE
Removed Unused Methods

### ISSUE THREAD

**Issue by KY-cloud1** [bejminliou/cis22c-project#30]
There's a lot of methods in different classes that we wrote but don't use, so I'm thinking we just remove them all in our finalized code. No point in having the methods if they're not used and, even if they can be useful, I doubt anyone will be touching the project's code once it's submitted so they'll probably never get implemented regardless. Minus well remove them just for code cleanup 🤷, what do you guys think?

**Comment by Askioe** [comment]
+1 I agree
